FROM neo4j:latest

ENV NEO4J_PLUGINS='["apoc", "graph-data-science"]'

RUN echo "dbms.security.procedures.unrestricted=apoc.*,gds.*" >> conf/neo4j.conf && \
    echo "dbms.security.procedures.allowlist=apoc.*,gds.*" >> conf/neo4j.conf

