services:
  # FastAPI Service
  fastapi:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile.fastapi
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_app:/app  # Bind mount for live code updates
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    networks:
      - my_network

  # Streamlit Service
  streamlit:
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile.streamlit
    container_name: streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/app  # Bind mount for live code updates
    depends_on:
      - fastapi
    networks:
      - my_network

  # Neo4j Service (for future use)
  neo4j:
    image: neo4j
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"  # Neo4j browser
      - "7687:7687"  # Bolt protocol
    volumes:
      - neo4j_data:/data
    networks:
      - my_network

# Volumes and Networks
volumes:
  neo4j_data:

networks:
  my_network:
    driver: bridge